### ISSUE TITLE
Constraint fails on foreign key

### ISSUE THREAD

**Issue by switz** [pddenhar/Subsonic-DB-Migration-Tool#1]
```
Starred media file Failed: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`subsonic`.`starred_media_file`, CONSTRAINT `starred_media_file_ibfk_1` FOREIGN KEY (`media_file_id`) REFERENCES `media_file` (`id`) ON DELETE CASCADE)
```

Any ideas?

**Comment by switz** [comment]
Just decided to comment this out as I don't really need it. Thanks for an awesome awesome lib!

**Comment by pddenhar** [comment]
I'm glad it worked for you! I wrote it as a one off to get out of a sticky situation so there might be some discrepancies with newer versions of Subsonic as the DB has changed.
